### ISSUE TITLE
Implement data model in blockstack

### ISSUE THREAD

**Issue by friedger** [COVID-19-electronic-health-system/Corona-tracker#111]
## Summary
Based on the [database model](https://github.com/COVID-19-electronic-health-system/Corona-tracker/tree/master/design/database_models), a data model should be added for managing user generated data.

Blockstack storage is a document/file based storage api, therefore the *database* model needs to be adapted. 

Suggestion:

Checkup 
* patient id (derived from blockstack user id)
* (same fields as in db model)

Settings
* doctors: doctor_id (public blockstack id)

Patients (for doctors only)
* List of patients (using blockstack collections??)

## Motivation
Data models help to simplify reasoning about data and abstract details about storing and retrieving data.

The above data model describes the data that the user generates, linking data in various ways can be added later if needed by publishing indexable data.

## Describe alternatives you've considered
There is no alternative to data modelling :-)

**Comment by ngiangre** [comment]
Is this a suitable model using NoSQL?

**Comment by ngiangre** [comment]
I made an entity relationship diagram when I stored data I scraped from a website. But @SomeMoosery said that an ER diagram doesn't make sense with our noSQL backend. So is there another way to relate data fields we want to collect?

Also, let's get out any doctor related fields since we changes the app's scope to more education/user self reporting/tracking.

I'm thing the survey Qs: https://docs.google.com/spreadsheets/d/1Ji0sxIqFI49EZb7Mz4F0nkSBn1JSNMXiKjFAzJC2Jso/edit should populate one field. How can we construct a data model with respect to our backend storage?

**Comment by SomeMoosery** [comment]
I'm going to link #114 to this as well, as it was my first pass of adding the checkup/evaluation models depending on questions we could ask - we'll probably end up changing a lot of the fields but the groundwork is laid in that PR if you both want to take a look
