### ISSUE TITLE
Investigate: @shopify/react-i18n- for handling translations, formatting, and more.

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#118]
## Summary
Investigate [@shopify/react-i18n](https://www.npmjs.com/package/@shopify/react-i18n) it is a i18n utilities for React handling translations, formatting, and more.

Architecture wise for i18n, code using properties (I.e key-value properties file).

This can be used for our translation into different languages.

See:
[https://en.wikipedia.org/wiki/Internationalization_and_localization](https://en.wikipedia.org/wiki/Internationalization_and_localization)

## Motivation
**Why are we doing this?** 
We need a way to use our translations in our file. This package helps with this.
We want our app to inform people in other countries before the wave of community infections start to overwhelm their health systems, especially in places with poor infrastructure. 

We can leverage the fact that internet connectivity is widespread to educate and share information.

**What use cases does it support?** 
Supports translation team's efforts

**What is the expected outcome?**
We have an already built way to support our translations in the file.

## Describe alternatives you've considered
Any alternatives can be considered. This was recommended by the systems architect advisor who has experience with this.

**Comment by friedger** [comment]
An alternative is https://github.com/i18next/react-i18next

**Comment by givonz** [comment]
react-i18n looks like it will do the trick.  i'm reading through it.  not totally sure how the translation files are to be made but, it follows the basic structure of all translation systems.  uses a code/key to get to the right translation per artifact.

i suggest we do not have different translations for different versions of english at this time
i suggest english be the default language
we need to name all the artifacts and texts so that people know what to translate and coordinate the translations

in addition, to hebrew, i may be able to provide french, dutch & malay.
