### ISSUE TITLE
Add functionality to Calendar to take user to Symptom Tracker Survey 

### ISSUE THREAD

**Issue by liadove** [COVID-19-electronic-health-system/Corona-tracker#214]
## Summary

- [ ] Add functionality to click on today's date (highlighted) and open symptom tracker survey
- [ ] Remove event handler callback

## Motivation

Should redirect to symptom tracker survey

Example view: 
https://raw.githubusercontent.com/COVID-19-electronic-health-system/Corona-tracker/master/design/wireframes/FINAL-V1-03.20/CORONATRACKER%20UI%20-%20Health%20Log%20-%20My%20Log.png

**Comment by JWaltuch** [comment]
I can probably take this. Just wanted to make sure I understand it. When clicking on today's date only (no other dates) it should simply redirect to the Symptom Tracker Survey?

**Comment by SomeMoosery** [comment]
I think for the time being, yes that's all we want to do. Just because we don't currently have a way of displaying already-completed surveys (no component to fetch that day's survey and display the data). Later on, we should have a way to display past surveys outside of the calendar and the functionality to click on any date and be brought to the component showing that day's survey, if that makes sense.

@liadove does that sound right?

**Comment by JWaltuch** [comment]
Hm... right now it's set up with React Hooks to just create an empty event when you click on the date.  Should I leave it as creating an empty event, and then have it redirect?

Based on my understanding of the app, it seems like the survey data will be stored in the database. So creating a calendar event in the database could be handled by the survey component, and the calendar data in the calendar component can be initially loaded from the database. If that's what we're going for in long term, it seems like I should just replace the whole event handler with the redirect, and then have the survey handle adding the event to the calendar once it's completed?

**Comment by SomeMoosery** [comment]
I agree! All really good points. Yeah, to keep this issue in scope, let's just remove the callback here and simply have it redirect to the survey page, since we won't be using this calendar to actually create events but just to redirect to certain dates, like you said. I'll create another story for persisting the story to the database, as those are distinct enough changes that they should be separate issues 👍 

I'll write that new ticket now so we don't lose context.

Really great points!
