### ISSUE TITLE
Enable front-end development without requiring a server

### ISSUE THREAD

**Issue by njordhov** [COVID-19-electronic-health-system/Corona-tracker#218]
## Summary

Make the app work without a server by adapting to having no access to Radiks.

## Motivation

Having the app also work without being connected to Radiks would immediately make development more approachable, as front-end development is possible without setting up a local backend and database.

## Additional context

For the longer run, it would be beneficial for the app to work even if servers are temporarily inaccessible or even for offline users. This could be a separate issue as it may require more work such as use of local storage and dynamic data synchronization.

## Related issues

#108

**Comment by SomeMoosery** [comment]
Is this something different than what I've quickly set up - running a Radiks server on a deployed AWS EC2 instance and setting the appropriate environment variable? This is obviously not built for scale but felt that it would satisfy our current needs.

I'm new to Radiks, so forgive my ignorance on the topic.

**Comment by SomeMoosery** [comment]
Oh, I think I see what you're saying. Basically, a strategy just so that the user can run just the frontend, and any necessary data we need to read in isn't queried through Radiks.

Would this require hard-coding in data? Are there any resources out there I could read up on? I'm not super familiar with Blockstack/Radiks and haven't really used a managed PaaS backend like this before, so any jumping-off points would be great!

**Comment by SomeMoosery** [comment]
Closing this for now for housekeeping purposes since we are currently halting the use of Radiks, it's been noted and will be re-opened (or a new equivalent issue with more updated context created) when the time arises
