### ISSUE TITLE
Github Cleanup: Readmes and Content Organization

### ISSUE THREAD

**Issue by whoabuddy** [COVID-19-electronic-health-system/Corona-tracker#324]
## Summary

After a general review of the repository, contributing guidelines, and code of conduct, I would like to propose some changes both to the content and organization.

## Motivation

The goal will be to create content that is easier to read, navigate, and digest based on the existing information.

## Describe alternatives you've considered

There appear to be no open or related issues.

## Additional context

I would like to take an approach similar to [this guide on contributing to Blockstack](https://app.sigle.io/whoabuddy.id.blockstack/s0zMy6UW3cTOfR-Lm9dCg) and the structure found in the [Stacks Foundation repositories](https://github.com/stacksgov), specifically [resources](https://github.com/stacksgov/resources).

I will open a related PR following this issue.

**Comment by tesla809** [comment]
This is a GREAT suggestion @whoabuddy ! Totally support it!

Let me know how I can help! Very excited about this.

**Comment by whoabuddy** [comment]
@tesla809 Thanks! For the testing section under "Technology Stack" it mentioned Jest - should this be TravisCI, ESLint, and Prettier now? Any others? (going off [PR#312](https://github.com/COVID-19-electronic-health-system/Corona-tracker/pull/312) as reference)

**Comment by SomeMoosery** [comment]
I think it's really a matter of semantic for how detailed we want to get with regards to tech stack. If we want to include nearly everything we're using, I'd say it would be something like this:

Frontend: React, ESLint, Prettier, Jest, 
Backend: Blockstack
Database: Gaia 
Deployment: AWS

For the time being. The issue here is that including packages like this is a slippery slope, because then some will be in the boat of "why not include MapBox?" and some will be in the boat of "Prettier isn't important enough to list" etc etc. Also, while we're probably not moving away from React, Blockstack, or AWS unless there's a crucial need to, there could always be the conversation to use a different formatter or linter, as those are less integral to the application itself.

That's why I'm personally a fan of keeping stacks simple (React/Blockstack/Gaia/AWS), but that's just me. Open to ideas!

**Comment by whoabuddy** [comment]
That makes sense, I like simpler always just expanded on some of what was there already. Plus that is a good point about avoiding the slippery slope. I'll try to get this and a few other small updates done tonight or tomorrow.
