### ISSUE TITLE
Temperature data not saved in the backend

### ISSUE THREAD

**Issue by pavel-ilin** [COVID-19-electronic-health-system/Corona-tracker#351]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

Related to issue #333 and #339 

When I open single observation json file from the Blockstack in DiagnosticContainer there is no temperature data in it. There is nothing to extract and pass to the Chart component.

### Steps to Reproduce

1. Open DiagnosticContainer
2. Add line   "const [observation] = useFile("observation/0000001.json");"
3. console.log(observation)

**Expected behavior:**

observation/0000001.json should contain numeric value which represents temperature which user submitted in SymptomsTracker component. 

**Actual behavior:**

observation/0000001.json doesn't contains numeric value which represents temperature which user submitted in SymptomsTracker component.

**Reproduces how often:**

100%

**Comment by SomeMoosery** [comment]
Is anything being saved in the database - like, is temperature being stored as a string? Or is nothing being saved at all?

If the former, we should just convert it to a number before posting to gaia - if the latter... that might be more of a problem with that specific question. 

Good catch! Are you willing to tackle this as well? Or should we leave this open for another contributor to take on while you work on the charts?

**Comment by pavel-ilin** [comment]
It think it's a problem with specific question. 
That's what I Blockstack give back:
![response](https://i.ibb.co/vk25LXF/Screen-Shot-2020-04-01-at-3-52-44-PM.png)

We can see that we have boolean value for the fever, but there is no key and value which will show us how high fever is.

Also I having a problem with using useFile hook for multiple files. If someone has experience work with it I would be happy to learn.

**Comment by SomeMoosery** [comment]
Hm... yeah, I'm not sure why off the top of my head but it looks like we aren't capturing [fever severity](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/37214e8d9b9b5857149d9edb2114da68285c6db0/client/src/components/survey-view/checkbox-button/CheckboxButton.jsx#L108) for some reason. 

We should look at the reducers in CheckboxButton and the way SingleCheckboxButton is handling data to make sure we're not losing anything in transit. Should I assign you to this since you're already working on the two charts? 

Also, for multiple files, I'd look to use [`listFiles`](https://blockstack.github.io/blockstack.js/classes/usersession.html#listfiles) as I'm not sure if the `useFiles()` hook handles multiple lists gracefully, but if anyone would know for sure it's @njordhov since `react-blockstack` is his brainchild :)

**Comment by liadove** [comment]
@pavel-ilin @SomeMoosery just fixed the issue with feverSeverity will make a PR in a minute

**Comment by njordhov** [comment]
> Also I having a problem with using useFile hook for multiple files. If someone has experience work with it I would be happy to learn.

@pavel-ilin There should be no problem using `useFile()` for multiple files. What happened?

**Comment by njordhov** [comment]
The `react-blockstack` library offers a `useFilesList` hook that returns the list off gaia filenames. It is undocumented but will be included in the official release shortly. Use like this:

    const [files] = useFilesList()

**Comment by SomeMoosery** [comment]
Awesome! Taking note of this 👍

**Comment by pavel-ilin** [comment]
@njordhov Thank you for your respond! Yes, I can get names of the all files with using useFilesList or listFiles, bu then I need to open each of the file and use it's content. I struggling with getting access to the each file content. I can't put useFile inside the loop or a function.

Thank you for your advice!

**Comment by njordhov** [comment]
> I can't put useFile inside the loop or a function.

As `useFile` is a hook for react you cannot put it inside a loop. The intended use in in a react function component. A typical pattern here is to have a component presenting the data from a single file, like say an observation, with filename as prop.

**Comment by SomeMoosery** [comment]
So if we wanted to, say, just loop through each `observationX.json` file and get one data point from each, would it still be best to use a combination of `useFilesList`, looping through the files, and `getFile` within the loop to read the data from each?

@pavel-ilin brought up the idea of potentially going back to the drawing board with our model and instead of storing observations as separate JSON files, storing one long `observations.json` file, appending each new observation to the end of it on creation - do you think this would be more advisable for our use case? As we could the just call `useFile('observation.json')` and then iterate through the JSON parsed from it?

**Comment by njordhov** [comment]
> instead of storing observations as separate JSON files, storing one long observations.json file

I recommend that you defensively store a read-only file for each and every observation. You can complement this with a file that contains the aggregated data you actually use, eventually including an index of the observation files.

That way, the database file doesn't become a single point of failure; You can always rebuild the aggregate from the set of single observations if there is a screw-up that messes up your database (or you decide to change how it is structured).

**Comment by njordhov** [comment]
> instead of storing observations as separate JSON files, storing one long observations.json file

I recommend that you defensively store a read-only file for each and every observation. You can complement this with a file that contains the aggregated data you actually use, eventually including an index of the observation files.

That way, the database file doesn't become a single point of failure; You can always rebuild the aggregate from the set of single observations if there is a screw-up that messes up your database (or you decide to change how it is structured).

**Comment by SomeMoosery** [comment]
Working on it #365
