### ISSUE TITLE
Update "Show Me More" to fit styling

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#370]
## Summary

- [ ] Work with @BrianHHough to make the new "Show Me More" tab more modern and user-friendly 

## Motivation

Moves us towards a more polished, finished UI

## Describe alternatives you've considered

Leaving it the way it is now

**Comment by AdhamAH** [comment]
If that means the `Table.jsx` component, this was built using bootstrap and I am planning to change it to material-ui. If so I will wait for @BrianHHough to tell me what to is the changes. 
If not I need more explanation

**Comment by kevin-Price** [comment]
@AdhamAH  Are you working on this? Im free to grab another story and was eyeing this.

**Comment by AdhamAH** [comment]
I was letting this a bet off because it looks good for now and wanted to try make the app bug free and polished. 
It is not just the style. First this should element the CSS file. Also I was planing to use one of the fixed header table form material-ui and add a search function to make it easier
If you think you can at least make the table I talked about with styling using Material-ui, sure by all mean go for it

**Comment by AdhamAH** [comment]
Or something else you think it could fit better, let me know

**Comment by kevin-Price** [comment]
Quick update on this: Refactored the bar chart into a line chart. Going to tackle the table next. Should be ready by tomorrow.

**Comment by SomeMoosery** [comment]
Great! Excited to see the PR!

**Comment by kevin-Price** [comment]
In lieu of some overlapping work to table.jsx on #460  -- should we cut the table changes out of scope here? And I can push up my changes to the chart?
