### ISSUE TITLE
Create mass mock data of observations

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#392]
## Summary

- [ ] Create a mass amount of semi-structured data based off our observations currently being created [here](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/7a8a24a9e70e65f95a85f54029e9ea90f4cfa2ad/client/src/components/SymptomsTracker.jsx#L116), and with any additional features @ngiangre may need

## Motivation

- While we won't be able to analyze real user data for some time, we want to start mocking data and seeing if we can
    - get things working with OpenMined
    - draw meaningful insights from the survey we're asking users

## Describe alternatives you've considered

- Waiting until users start entering data (we don't have that luxury of guaranteed users)

## Additional context

- Work closely with @ngiangre and the Analytics team to ensure data is created and structured to their specifications

**Comment by ngiangre** [comment]
Mock data would be much appreciated and needed!

**Comment by pavel-ilin** [comment]
I can create Rails API and generate massive amounts of data with faker gem based on what we need to practice analytics.

**Comment by SomeMoosery** [comment]
That would be awesome! I'm not sure if you have access, but if you do you should edit the issue with what your plan will be for this (what you'll build, how you'll build it, inputs/outputs, how we could deploy it, etc). I don't have any experience with Ruby myself, so you can definitely take ownership of this if you'd like!

**Comment by pavel-ilin** [comment]
Alright, I'm on it! 

@SomeMoosery  I don't have access to this issue, but I can create new one.

@ngiangre Could you please provide parameters of the mock dataset. Models, attributes and size (how many entries).

**Comment by ngiangre** [comment]
@pavel-ilin sorry for the delay I'm just seeing this. 

Like in the call, you can use the observation -> physical fields in here https://docs.google.com/spreadsheets/d/1Ji0sxIqFI49EZb7Mz4F0nkSBn1JSNMXiKjFAzJC2Jso/edit?usp=sharing as predictors and the observation -> coronavirus fields 

Use the data ranges specified. 

We need to make sure any analysis/prediction works as expected. Can you, say, "spike" the dataset so that those users that answered index 41 as yes to have high scores for a few of the physical observations? Like give those that said yes a few milds, and a lot of moderates and severes and those that said no a lot of milds, and a few moderates and severes. You can randomly distribute values for the other coronavirus observation fields. 

Let me know if we should hash this out more.

**Comment by pavel-ilin** [comment]
Should we move thus issue to the Analytics repo? I can create new issue there and add Rails API to the repo.

**Comment by SomeMoosery** [comment]
Agreed - good point @pavel-ilin 

Let's just be sure to capture the context here and link it in the new issue in Coronalytics 👍
