### ISSUE TITLE
Discussion - create seperate databases for patient-related data from other data?

### ISSUE THREAD

**Issue by sedmo** [COVID-19-electronic-health-system/Corona-tracker#43]
All HIPAA related data should be block-stack related 

Whereas data in **news** is covid19-tracker wide

and then **maps** is geolocation wide

and finally **settings** is saved by cache

Will need a further discussion where data is discussed especially in regards to geolocation data

**Comment by SomeMoosery** [comment]
Agree that HIPAA-related data can (is currently being worked on) and will be in Blockstack storage using Gaia and Radiks to query. 

With regards to news and maps - what kind of data do you think we'll need to be storing ourselves here? I was thinking we could potentially store the users' coordinates in a cookie for faster loads, but other than that I feel like all news and geolocation information can be scraped from the internet or accessed in real-time via and API.

The only other thing that I think would need to be stored would be where certain users have pointed out resources (such as "There's Tylenol at the Duane Reade on 34th and 3rd"). I think since the map functionality is more for once we have an IPR out the door, we can put the on the backburner for now. That being said, this is a good point and definitely something to consider.

I had tried to keep it in mind even though we won't be dealing with this for some time (at least until the symptom-tracker is done and polished), but I personally don't see much harm in storing the location-based data in Gaia and accessing via Radiks as well. Unless that violates HIPPA-compliancy regulations. Gaia is simply a decentralized key-value store which could work well with a model like `Tylenol:<some-coordinates`. This would be easy to access with Radiks, which basically just allows you to query this decentralized data.

**Comment by SomeMoosery** [comment]
Going to close this for the time being after the call with Dr Zatakia led us to change direction again, and we won't be worrying about HIPPA-compliance for now. 

Because of this, we can associated all relevant data with each Blockstack user, at least for the time being.
