### ISSUE TITLE
Scroll bug on pages like onboarding, about, etc

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#442]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

I think because we have components like `Layout`, `Scroll`, etc we are getting some weird behavior on mobile when scrolling on pages like `Onboarding` and `About`.

![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/15767602/78932984-7ff95e00-7a76-11ea-924f-f5e9e39f27ae.gif)

### Steps to Reproduce

1. Login
2. Navigate to onboarding and attempt to scroll

**Expected behavior:**

Scrolling is smooth and seamless

**Actual behavior:**

Can be a challenge to scroll down the page

**Reproduces how often:**

~75%

### Versions

0.3.10

**Comment by AdhamAH** [comment]
We are not using scroll component as it is not needed any more and yes it might because of the layout component but that's not all. Mainly It is the position of the navBar and I think if we remove the layout and add the logos to every other page( I actually tried) the same results are produced. Add to that the device browser plays a part. On my mobile which android and chrome I am not facing this problem. 

I did a fix in a PR, try it and let me know
