### ISSUE TITLE
Improve observation blockstack db interactions

### ISSUE THREAD

**Issue by fallon7284** [COVID-19-electronic-health-system/Corona-tracker#457]
## Summary

I think that there is an issue there around fetching observations as their number grows that might need addressing, and I've meant to bring it up for a long time.  

The way we do it currently we list all files, iterate over that list returning a list of all files whose name includes "observation/", and then fetch each of those files one by one.  

Similarly when we create a new observation we do this thing where we have to list and count all of the files in order to determine the name of the next file we create.  

I think that we could just have a single 'observation' file which contains a json string array of all the observation objects.  Fetching all the observations would just look like JSON.parse(usersession.getfile('observations')) and adding an observation would just mean adding the new observation to that array and userSession.putFile('observation', JSON.stringify(that new objservations array))

## Motivation

Turn these exponential operations into constant time. Really simplify all the blockstack db interactions.

**Comment by fallon7284** [comment]
Unless there is some constraint that I don't understand re: blockstack/gaia that forces us to do it the way we do it currently.

**Comment by SomeMoosery** [comment]
Nope, you're definitely correct - this has been something that's been needed for a while and has actually been brought up in a couple other conversations. I've pushed back in the past only because we wanted to ensure we had basic functionality working first before optimizing, but this is definitely needed.

From what I've gathered, common practice would be creating a master `observations.json` file to put into Gaia. This would be the primary object we read in observations from and add objects to. 

And as a measure of redundancy, on observation creation, we would create an additional `observation/000xxx.json` so that in case `observations.json` somehow was corrupted or lost we could recreate it from original observations.

**Comment by SomeMoosery** [comment]
If you want to take this on it would be a huge optimization a huge optimization - would you be willing to?

**Comment by fallon7284** [comment]
Yeah, it would be a lot of work.  I'd be willing but I can't commit to getting started on it right now, busy with job search stuff right now.  So if someone else wants to grab it that's fine, and if nobody does then I'll do it when I have some time.

**Comment by SomeMoosery** [comment]
Sounds good - I'll leave this open for now and if you find time for it just comment again and I'll assign you 👍.

It's good looking out because, yeah, especially when we grow this is something that'll certainly need to change.

**Comment by njordhov** [comment]
The observations file can be kept in the browser's localstore rather than gaia. If lost (or user change device) it can always be generated from the observation files in gaia.

**Comment by SomeMoosery** [comment]
I had actually already brought this up in #365 - could be worth checking to see if there's any additional helpful context there

**Comment by fallon7284** [comment]
I'm working on this.  It is likely to take a good long while.
