### ISSUE TITLE
Delete observation functionality

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#476]
## Summary

We want to give users the ability to delete any observation they wish

**Acceptance Criteria** 

- [ ] Add ability to swipe right on a WeeklyTracker for a specific observation
- [ ] on right-swipe, implement a `Dialog` asking if the user is sure they want to delete, and then a redux thunk to delete that observation (using Gaia `deleteFile()`)
- [ ] update UI to reflect that deleted observation

## Motivation

Both to give users a sense of ownership over their data (since they do own it) and... for way down the line... to comply with GDPR guidelines that users should always be able to delete their data upon request.

## Describe alternatives you've considered

None, this is necessary

**Comment by JWaltuch** [comment]
I could probably take a crack at this tomorrow

**Comment by JWaltuch** [comment]
To clarify, is this replacing the Weekly Tracker Day right swipe, where currently it loads the stats for that weekly tracker day?

**Comment by SomeMoosery** [comment]
Ah no, sorry. We want to be able to swipe the other direction (or, if you have another suggestion like maybe just putting a trash can icon on the `WeeklyTrackerDay` or something let me know!).

And whenever we swipe (or click, etc - whatever you think is best) it will first create a `Dialog` asking if the user wants to delete the file - and then on confirmation removes the files from Gaia using `deleteFile`

**Comment by JWaltuch** [comment]
Ah, thanks! I've got it popping up when the user swipes left and triggering the thunk on "yes".

I also haven't done much with Gaia yet, so I'm trying to understand the best way to do this, if anyone can help a bit. It looks like when observations are added, they are added both to a main observations JSON file AND a separate JSON file with a file number. Assuming I'm correct about that, my initial thinking is that maybe I could somehow identify an observation in the main observations file by the date and overwrite it? I'm not sure about how to find the file by number though, since the number doesn't seem to be recorded anywhere beyond in its file name. And it looks from the docs like deleteFile needs the file name to find which file to delete. Should I modify our observation records to include file numbers? Or am I missing something?

**Comment by fallon7284** [comment]
This is actually an interesting problem, because the way we are generating the filenames for those individual files is simply by looking at the length of the array of observations in the observations.json file, so if we are to remove an observation from that observations.json file, we'll throw that process out of sync.  A simple but maybe too hacky solution might be to simple replace the observation in the observations.json array with a null value or something in order to maintain the same length so that we can keep those backup files in sync with the main observation.json.  In which case, maybe you just find the observation by the date stamp, replace it with null, and then use that array index to looked the single file to delete which would just be observations/00000x where x is index + 1.

**Comment by fallon7284** [comment]
Maybe a better long term solution is actually that observations.json is an object where keys are the date and the name of the single file is also just like observations/{theDate}.json

**Comment by JWaltuch** [comment]
I could change it to add by date if that makes better sense. The date would always be unique, right?

**Comment by fallon7284** [comment]
Yeah the date would always be unique.  It is sort of a large change that goes well outside the scope of this issue.  

I wonder if the sort of hacky solution of just replace it with a null value is ultimately still perfectly acceptable?  It would just require a small tweak in the fetch thunk to filter out those null values from the list we add to the redux store.  

Otherwise like I said it's a much larger change.  @SomeMoosery Thoughts?  I just changed this 2 days ago but honestly hadn't considered that we would want to delete observations or I would have just done what i proposed above in the first place.

**Comment by JWaltuch** [comment]
Yeah, that's why I wanted to check what we all want for a large scale before I move forward with it :)

**Comment by SomeMoosery** [comment]
So this issue actually wasn't high priority until discussing with legal teams very recently - so as it stood what you implemented was a perfect solution @fallon7284 

That being said, it's become clear that we really ought to provide the user a way to delete all of their data if they so wish. I'm rethinking this issue and nuances behind it now that these points have been brought up. From a selfish perspective, we would prefer if users didn't delete their observations. Perhaps a simpler representation would be to add a button in the `More` or `Onboarding` components, which after pressing and confirming wipes all user observations from the database and starts clean. I know you added a commented-out "kill switch" in your last PR @fallon7284 - maybe we could use something similar. This suffices for the user being able to delete all data if they so wish, but encourages them to not do such.

I think that the solutions you provided would be a great longterm fix though, @fallon7284 - because at the end of the day we don't want to make users feel like we are strong-arming them into keeping their data. But maybe not for Friday's beta launch.

Thoughts? This is an interesting conversation

**Comment by JWaltuch** [comment]
I'm no legal expert, but for privacy reasons and legal reasons, it certainly feels like a delete all would satisfy it. Because if the issue is that a user isn't comfortable with having the data stored, they CAN delete it all at any time. And I agree that we kind of don't want to encourage them to just delete random observations because it skews their data as a whole.

I can vaguely imagine being a user thinking 'oh, I want to delete only Monday's data' if I said something I wanted kept private on Monday and then rethought things and regretted it, I suppose. And then a downside to delete all being the only option means I lose all my data and have to start again. That seems like kind of an outlying case though.

For what it's worth, I have an app installed on my phone where users save medically related data, and there is the option to delete each record. But I don't know if that is to cover themselves legally or because they felt that was a good app feature.

**Comment by SomeMoosery** [comment]
Yeah I think it's definitely a good feature to have - and something we should implement as we go forward. I'm just thinking from a liability standpoint and for the scope of this issue - we should just add the bare minimum "Delete All" functionality for Friday and then build off of that.

If you want to get started on that - adding that functionality will always be useful no matter what. I can circle back with our legal counsel and get their thoughts on deleting all vs deleting individual and if there's a differentiation there in the eyes of the law.

**Comment by fallon7284** [comment]
Yeah so I think I deleted that commented out deleteAll function now, but it should be easy enough to write, you just need to checkout how listFiles works.

**Comment by JWaltuch** [comment]
Okay :) I have functionality right now on left swipe of an observation, but if we're deleting everything I don't know if that makes sense? Should I make a button somewhere for Delete All?

**Comment by SomeMoosery** [comment]
Yeah, maybe another button or additional to the `More` popup? Maybe something that runs across the bottom of it?
