### ISSUE TITLE
Implement Analytics 

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#491]
## Summary

- [ ] Set up analytics of some form

Basic functionality should include
- [ ] Track page views
- [ ] Track locations page was accessed
- [ ] Track how long user stayed on site

Advanced functionality we should include
- [ ] Track load performance 
- [ ] Track how long user stays on each page
- [ ] Track rendering performance
- [ ] Track scroll
- [ ] Track events 

## Motivation

Once we release Friday, we want to be able to get insights into how users are using our app to learn how to best move going forward

**Comment by SomeMoosery** [comment]
I'm on this

**Comment by johnemurphy1** [comment]
@SomeMoosery let me know if you need any help. 10+ years on the user side and basic web implementation.

**Comment by SomeMoosery** [comment]
Sounds good, thanks @johnemurphy1 !

**Comment by SomeMoosery** [comment]
So I've retitled and reformatted this issue. Google Analytics may not be the best strictly in terms of vision here. Google analytics, while not collecting any personal information from users, is using all of these analytics just as we are - it's why their service is free. CoronaTracker is aimed at being open-source and community-driven, with user empowerment in mind. Integrating with GA behind the scenes might be a bit of an ethos hit.

If anyone has a defense of GA, feel free to let respond here. I know it does not collect (Google-defined) [PII](https://support.google.com/analytics/answer/7686480), but it's still a question to consider. GA may also pose a GDPR issue down the line, and would be a fine line to walk.

Otherwise, some alternatives I was considering (at least for the time being are).

- [Plausible](https://plausible.io/)
- [Fathom](https://usefathom.com/)
- Implementing our own rudimentary analytics for the very near term (ehh..)

Please share your thoughts below!

**Comment by kevin-Price** [comment]
Analytics for performance is a great idea. For this particular data point: "Track how long user stays on each page" - does it make more sense to ask the users? IE In the form of a feedback page/feedback popup. 

Im thinking instead of tracking that Bob spends a lot of time on page x, we can ask Bob what he thinks about the application. 

Im wondering what the goal behind that metric is. Spending a lot of time on a page can lead me to think either its useful and displays lots of information - therefore one stays on it for a while, or its difficult to use and hard to navigate - also staying on the page longer than expected

**Comment by SomeMoosery** [comment]
Good points, I was really just thinking of some general things that we could track. I know if we go with something like Fathom, they provide a streamlined dashboard of key metrics, so it would really just be what they provide in the end. 

Anything we get on an analytics side should definitely be done in tandem with user surveys, though! Which are well in the works

**Comment by johnemurphy1** [comment]
Since we're a new app, we should track things like bounce rate, sign up
completions, retention, etc. Not familiar with Fathom, but will start
researching now.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by kevin-Price** [comment]
@johnemurphy1  I 100% agree with those metrics. Definitely useful things to track for a first app. 

In regard to user feedback, I spun up an issue on that: #489   - Ill go refine it into a user story
