### ISSUE TITLE
Add message after failed subscribe

### ISSUE THREAD

**Issue by acthelemann** [COVID-19-electronic-health-system/Corona-tracker#539]
## Summary

If a user fails to subscribe a phone number - the phone number could have already been subscribed in the first place or there could be an internal server error - display a message explaining that it failed.

- [ ] Display message that phone number was already subscribed if service returns a `409` status code
- [ ] Display generic error message for any other failing status code

## Motivation

User should know when their subscribe request failed.

**Comment by AdhamAH** [comment]
I don't want you to work more than you thought the issue is @luky1300 
But if you could take a look at [this](https://material-ui.com/components/snackbars/#snackbar) and maybe try to use it.
you can use something like  a `const response = []` and use `response.push('Subscribed successfully! .....')` function to push the message in place of `alert` 
then `map` through `response` to make the `Snackbar`
or any way you see it fit 
just an idea I was thinking about it.

**Comment by luky1300** [comment]
@AdhamAH, thank you for your comment and for bringing this up! I totaly agree that the Snackbar looks more appealing. I will try to implement that.

**Comment by AdhamAH** [comment]
Great! Try it but don't feel obligated to do it, it is just a suggestion.
But I assure you will feel pretty good when you see it working. I know from experience😁
