### ISSUE TITLE
Testing front-middle-back end communication

### ISSUE THREAD

**Issue by ngiangre** [COVID-19-electronic-health-system/Corona-tracker#59]
Y'all ready to start a mock survey and recording user data, storing it, and then populating charts?? I can help with survey design, data models, and chart population within components. I just need a developer and a database person to help me figure out how to be the "middle man" and prototype/launch stuff.

**Comment by SomeMoosery** [comment]
I was actually just typing out a message into Discord when you sent this in. I've been working on setting up a serverless backend and database connection on the Blockstack platform (my [current issue](https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/48) is actually fleshing out the models for storing/retrieving user data since I've just recently set up a auth with Blockstack and the ability to get user information). 

I think before we start with this, I think we should all have a discussion (maybe some time tomorrow/Wednesday afternoon if we can work around the calls with the startup founder and emergency pulmonary specialist) to finalize the user flow so that we can finalize models. Once we have this settled, I agree that we can definitely start populating charts with some mock data. 

I'm going to add a long-ish comment to [this issue](https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/9) regarding database models / when we can all chat (ideally over Zoom or something) / learnings from working with Blockstack

**Comment by SomeMoosery** [comment]
In terms of populating data, we are also only running this application locally right now. Therefore, in order to populate the charts, we'd probably have to have some kind of script to create and populate collections on app startup. That shouldn't be too difficult with React, but just something to keep in mind for the time being.

**Comment by ngiangre** [comment]
Conversation from discord: Hey @Carter I'm going to respond to the issue on data model/analytics. 1) I'm hesitant to have the app show individual level data because of privacy concerns (one can be more easily identifiable). 2) The app you shared on modeling covid exp. growth is honestly not helpful it's giving an upper bound to how bad things can get with infection rates but it doesn't tell ppl what they can do. 3) Individual user feature: I advocate a symptom/infected probability function over geographic areas at the neighborhood level so as ppl can decide for themselves if they should stay clear. I'll put this and more in the issue. 4) Healthcare user feature: I honestly don't know or think healthcare users will use this given they'd want "tried and trusted" systems but then again if there's no prep then this might be useful. I have no suggestion though

**Comment by ngiangre** [comment]
Hey @SomeMoosery I'll check out that comment. I agree let's hop on a call after the startup/MD calls so we have a better idea what to mock up.

**Comment by ngiangre** [comment]
this issue seems irrelevant the conversation should go to a targeted topic
