### ISSUE TITLE
Some thoughts regarding the application

### ISSUE THREAD

**Issue by hmalik88** [COVID-19-electronic-health-system/Corona-tracker#66]
1. For this to really take off the whole nation needs to be on the app. What's the incentive to be on the app as opposed to just watching the news and staying clear of pockets of high infection. What's the plan to get people on board at scale?
2. Who's the target audience? Essential workers in sectors such as healthcare, transportation etc? Most people are in self-quarantine right now and WFH so they won't be going outside much.
3. How specific are we getting when it comes to marking locations on the map as to an infection location? Are we marking neighborhoods? Individual homes? The concern is the privacy aspect, because if you're marking individual homes then it's easy to figure out who lives there, especially if you live on the same street.

**Comment by nathanboone** [comment]
Hey hmalik88,

**This app has two value propositions**
1.   For Users: Aggregate, credible up-to-date information translated into Spanish or Arabic, as well as a one-stop shop for English speakers to find everything they need on prevention (air, surface, etc.) spread (infections reporting and connecting to screening apps)

2.   For Public Health Officials: Aggregate, macro-view of patients PRIOR to initial screening, who are engaged and reporting symptoms

**Target audience -** Users seeking out information, primarily ages 25-45. Especially those who would like to self-report their symptoms in an effort to engage proactively in their own health monitoring

Marketing Location - I suggest at the city level, but defer to our team-members with a data anonymization background. Privacy concerns are less pressing since this is publicly reported data, and self reported data.

**Comment by SomeMoosery** [comment]
Great points, Nathan! I'm just commenting as a remind to edit this comment with a few additional points / updates tomorrow. Mainly, after a call with a pulmonary doctor this evening, that we decided targeting already-overwhelmed public health officials who are unlikely to trust the information we collect until we reach scale and are HIPPA-compliant is out of scope.

Will comment with more details tomorrow - but all great points! Just want to add my two cents as well :)

**Comment by ngiangre** [comment]
For this to really take off the whole nation needs to be on the app. What's the incentive to be on the app as opposed to just watching the news and staying clear of pockets of high infection. What's the plan to get people on board at scale?
- The app will be a clear, no nonsense decision tree of guidelines that each user clicks through. The plan is to disseminate through social media channels and get public health officials on board to include in their suggested apps and newsletters to our targeted population. 

Who's the target audience? Essential workers in sectors such as healthcare, transportation etc? Most people are in self-quarantine right now and WFH so they won't be going outside much.
-See https://docs.google.com/document/d/15i7vBDCFqGHCf3B-D9Miw0_3I1M6_rn3v4fzA1PAAK4/edit#heading=h.o2dkx9wkrwkg. he audience will be those less likely to abide by social distancing and more likely to be caregivers for at risk populations with comorbidities and immunocompromised systems. 

How specific are we getting when it comes to marking locations on the map as to an infection location? Are we marking neighborhoods? Individual homes? The concern is the privacy aspect, because if you're marking individual homes then it's easy to figure out who lives there, especially if you live on the same street.
-it should be neighborhoods - zipcodes. And we ca avoid showing counts and instead show probabilities of our user characteristics to obscure individual identifiability.

Thoughts?

**Comment by SomeMoosery** [comment]
@awu556 @tesla809 or anyone else willing - would you want to consolidate these notes into another document we have and then close this issue? Just to clear out our backlog.

**Comment by awu556** [comment]
Sure! I'll do it right now in a google doc

**Comment by awu556** [comment]
Alright, all set. Feel free to close or delete the issue
