### ISSUE TITLE
[FEAT] Allow to toggle between Celsius or Fahrenheit with automatic conversion

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#682]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement the feature.

### Prerequisites

- [x] check this box if you have completed the following:
    - Reviewed the [contributing guidelines](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md) and [support](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md) files
    - Reviewed the README file for the repository you are working in
    - Searched for relevant instructions [on our Discord server](https://discord.gg/pPERUuv)
    - Searched the issues of the repository you are working in to make sure one was not already filed

### Summary

According to first user in field DocMusher- "the way temperature is mentioned is ok. Does a patient has the choice between Celcius and Fahrenheit?"
In order to have this ready for MVP, we need the temperature to be able to be in Celsius.

Most of the world uses the metric system and Celsius. 

Set to Celsius by default. Allow the user to toggle between Celsius and Fahrenheit with a button. If user toggles between button, the values are converted automatically. 

Celsius to Fahrenheit equation: 
Divide by 5, then multiply by 9, then add 32

Fahrenheit to Celsius :
Deduct 32, then multiply by 5, then divide by 9

### Motivation
**Why are we doing this? **
Dutch users for MVP use Celsius not Fahrenheit.

**What use cases does it support?**
Getting app ready for MVP

** What is the expected outcome?**
Users can toggle between  Celsius and Fahrenheit easily.

### Possible Alternatives

This is pretty low cost with extra convenience for the user.
We can just have a default button without styling we can use instead of a custom button. 
But let's make it look nice if we are at it. 

### Additional Context

According to first user in field DocMusher- "the way temperature is mentioned is ok. Does a patient has the choice between Celcius and Fahrenheit?"

**Comment by fallon7284** [comment]
I can do this.

**Comment by fallon7284** [comment]
Quick thought, and I'd like some other folks input on it before I offer to take this issue:
My assumption is that we will want the temperature represented in the data consistently across users, either as Celsius or Fahrenheit (and I'm assuming Fahrenheit, because that's what it is currently) and the toggle will simply turn on/off the function of converting between the two units in the input field and anywhere temperature is displayed.
So this is an app-level state change, correct?  We're going to need to add a field on gaia that says whether this user has chosen to use fahrenheit or celsius?  And then have that field in our redux store that tells components whether or not to convert where they need to convert.  And that conversion will have to happen in every component where we collect or display temperature.
That way a user who has chosen fahrenheit will also see temperature displayed in fahrenheit in other components, and will not have to re-select fahrenheit as their preferred unit every time they use the app.
This feature seemed simple at a glance but maybe there's a bit more to it.
Does this sound right or do others have a different view of what is the behavior we want when this is done or how to get there?

**Comment by fallon7284** [comment]
I'm working on this, but I think it's likely to require some other changes in response.   I'm only guessing but I think it will make the component where we chart temperature over time look funny or inconsistent between measures, for instance.

**Comment by fallon7284** [comment]
You guys can assign me this.  I've got it mostly done, but I have a couple tricky little problems.
