### ISSUE TITLE
Use connect.js lib instead of blockstack.js

### ISSUE THREAD

**Issue by friedger** [COVID-19-electronic-health-system/Corona-tracker#93]
connect.js library simplifies the on-boarding a lot.

**Comment by SomeMoosery** [comment]
Are you saying we don't utilize blockstack? At this point, at least for an MVP, we've kind of set up a good amount of scaffolding for it so to get it out the door I'm thinking we should stick with Blockstack, but if I'm missing context feel free to fill me in. 

The choice to go with Blockstack was to have both a serverless backend and to protect data privacy (we, nor AWS/Azure/GCP have the ability to make use of any of the users' data). I do agree, though, that maybe in the longterm we look for an alternative or complementary way for users to log in since Blockstack is not very ubiquitous.

Can you link the package as well? The only thing I found titled `connect-js` was a deprecated Facebook package. There was `connect` as well, but I don't know if this is what you were referring to.

**Comment by tesla809** [comment]
Yea, some more description around the PR is needed @friedger 

This is a major change to the design, so some description of benefits is needed.

The MVP is predicated on using [Blockstack](https://docs.blockstack.org/storage/overview.html), at least for now. We can add additional sign-in methods, but to avoid any HIPPIA issues, we choose Blockstack to decentralize the data so the user controls it. Any data that is centralized is encrypted by default with [Radiks](https://github.com/blockstack/radiks).

**Comment by friedger** [comment]
The repo for connect is https://github.com/blockstack/ux/tree/master/packages/connect
It is improved UI for Blockstack

**Comment by SomeMoosery** [comment]
Oh, nice, I hadn't seen this before. I'll do some looking into it but I feel like it could definitely be worth integrating!

**Comment by friedger** [comment]
These are the changes to use connect.js : https://github.com/friedger/Corona-tracker/commit/8f230249b4eddd6e351ae060fee7530133b69d3d

I am happy to prepare a pull request

**Comment by SomeMoosery** [comment]
PR would be great! Said the same on your comment as well 👍
